'use strict';
const { contextBridge, ipcRenderer } = require('electron');

// contextIsolation is on and nodeIntegration off, so this allowlist is the
// entire renderer-facing API surface.
contextBridge.exposeInMainWorld('konnect', {
  getStatus: () => ipcRenderer.invoke('status:get'),
  listDevices: () => ipcRenderer.invoke('devices:list'),
  connectDevice: (mac) => ipcRenderer.invoke('devices:connect', mac),
  disconnectDevice: () => ipcRenderer.invoke('devices:disconnect'),
  selectDevice: (mac) => ipcRenderer.invoke('device:select', mac),
  forgetDevice: () => ipcRenderer.invoke('device:forget'),
  verifyLink: (mac) => ipcRenderer.invoke('device:verify', mac),
  boundMac: () => ipcRenderer.invoke('device:bound-mac'),
  dial: (n) => ipcRenderer.invoke('call:dial', n),
  liveCalls: () => ipcRenderer.invoke('calls:live'),
  answer: (id) => ipcRenderer.invoke('call:answer', id),
  hangup: (id) => ipcRenderer.invoke('call:hangup', id),
  sendDtmf: (d) => ipcRenderer.invoke('call:dtmf', d),
  runSetupChecks: (mac) => ipcRenderer.invoke('setup:check', mac),
  remediate: (id, mac) => ipcRenderer.invoke('setup:remediate', id, mac),
  listCalls: (o) => ipcRenderer.invoke('calls:list', o),
  callStats: (o) => ipcRenderer.invoke('calls:stats', o),
  listContacts: () => ipcRenderer.invoke('contacts:list'),
  importContacts: () => ipcRenderer.invoke('contacts:import'),
  cancelImport: () => ipcRenderer.invoke('contacts:cancelImport'),
  getSetting: (k) => ipcRenderer.invoke('settings:get', k),
  setSetting: (k, v) => ipcRenderer.invoke('settings:set', k, v),
  listAudioDevices: () => ipcRenderer.invoke('audio:devices'),
  getPcVolume: (n) => ipcRenderer.invoke('volume:pc:get', n),
  setPcVolume: (n, p) => ipcRenderer.invoke('volume:pc:set', n, p),
  getCallVolume: () => ipcRenderer.invoke('volume:call:get'),
  setCallVolume: (p) => ipcRenderer.invoke('volume:call:set', p),
  getMicMute: () => ipcRenderer.invoke('mic:mute-get'),
  setMicMute: (on) => ipcRenderer.invoke('mic:mute-set', on),
  testRing: () => ipcRenderer.invoke('ring:test'),
  stopRing: () => ipcRenderer.invoke('ring:stop'),
  dismissIncoming: () => ipcRenderer.invoke('incoming:dismiss'),
  chooseRingtone: () => ipcRenderer.invoke('ring:choose'),
  exportCallsCsv: () => ipcRenderer.invoke('export:calls-csv'),
  exportContactsCsv: () => ipcRenderer.invoke('export:contacts-csv'),
  exportContactsVcf: () => ipcRenderer.invoke('export:contacts-vcf'),
  exportReportPdf: (range) => ipcRenderer.invoke('export:report-pdf', range),
  revealRecording: (p) => ipcRenderer.invoke('recording:reveal', p),
  getAutostart: () => ipcRenderer.invoke('autostart:get'),
  setAutostart: (on) => ipcRenderer.invoke('autostart:set', on),
  windowMinimize: () => ipcRenderer.invoke('window:minimize'),
  windowMaximize: () => ipcRenderer.invoke('window:maximize'),
  windowClose: () => ipcRenderer.invoke('window:close'),
  adapterPower: () => ipcRenderer.invoke('adapter:power-get'),
  setAdapterPower: (on) => ipcRenderer.invoke('adapter:power-set', on),
  startScan: () => ipcRenderer.invoke('scan:start'),
  stopScan: () => ipcRenderer.invoke('scan:stop'),
  pairDevice: (mac) => ipcRenderer.invoke('pair:start', mac),
  confirmPairing: (ok) => ipcRenderer.invoke('pair:confirm', ok),
  registerPairingAgent: () => ipcRenderer.invoke('pair:register'),
  unregisterPairingAgent: () => ipcRenderer.invoke('pair:unregister'),
  onStatus: (cb) => ipcRenderer.on('status:changed', (_e, s) => cb(s)),
  onCall: (cb) => ipcRenderer.on('call:changed', (_e, c) => cb(c)),
  onCallsChanged: (cb) => ipcRenderer.on('calls:changed', () => cb()),
  onContacts: (cb) => ipcRenderer.on('contacts:changed', (_e, l) => cb(l)),
  onCallVolume: (cb) => ipcRenderer.on('callvolume:changed', (_e, v) => cb(v)),
  onMicMute: (cb) => ipcRenderer.on('micmute:changed', (_e, on) => cb(on)),
  onRouting: (cb) => ipcRenderer.on('routing:changed', (_e, r) => cb(r)),
  onAdapterChanged: (cb) => ipcRenderer.on('adapter:changed', (_e, s) => cb(s)),
  onScanDevice: (cb) => ipcRenderer.on('scan:device', (_e, d) => cb(d)),
  onPairingRequest: (cb) => ipcRenderer.on('pair:request', (_e, r) => cb(r)),
  googleStatus: () => ipcRenderer.invoke('google:status'),
  googleSignIn: () => ipcRenderer.invoke('google:sign-in'),
  googleSignOut: () => ipcRenderer.invoke('google:sign-out'),
  googleSyncContacts: () => ipcRenderer.invoke('google:sync-contacts'),
  googleBackupNow: () => ipcRenderer.invoke('google:backup-now'),
  onGoogleChanged: (cb) => ipcRenderer.on('google:changed', () => cb()),
  // A tel: link the user opened elsewhere. Prefills the dialer; never dials.
  onDialPrefill: (cb) => ipcRenderer.on('dial:prefill', (_e, n) => cb(n)),
});
